//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyPackageHistory
    {
        public int ID { get; set; }
        public int PackageID { get; set; }
        public int CustomerID { get; set; }
        public long Price { get; set; }
        public Nullable<System.DateTime> ConrfirmDate { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CodeVNPay { get; set; }
        public string KeyVNPay { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ServicePackage ServicePackage { get; set; }
    }
}
