//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public int BatchID { get; set; }
        public Nullable<int> CustomerActiveID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IsActive { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
